########################################################################
#
#
# pipeline_intro_1.py configuration file
#
# This pipelineyml file contains parameters to configure pipeline run
#
# Add pipeline specific options into separate sections
#
########################################################################
## general options these are essential options that must be specified 
## for every pipeline run.
general:

    database: csvdb


########################################################################
#
## There are no other pipeline options, but if there were you could 
## specify them here. See pipeline_hello_world.py for more detail
#
########################################################################
